# Deploys to linode instance
# (Doesn't currently actually deploy)

name: Next.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:	
    runs-on: ubuntu-latest
    
    env:
      SERVER_DESTINATION: /var/www/rimmer-blog/
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build the Next.js app
        run: npm run build
        
        
      - name: Update known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude='.env'
          remote_path: ${{ env.SERVER_DESTINATION }}
          remote_host:  ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user:  ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}

      - name: SSH into server and run migrations
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ env.SERVER_DESTINATION }}
            npx prisma migrate deploy
