# Deploys to linode instance
# (Doesn't currently actually deploy)

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:	
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.5.3
      
      - uses: actions/setup-node@v2.5.2
        with:
          # update the Node version to meet your needs
          node-version: 18
          cache: npm
	  
      - name: Build
        run: |
          npm ci
          npm run build
