# Deploys to linode instance
# (Doesn't currently actually deploy)

name: Next.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:	
    runs-on: ubuntu-latest
    
    env:
      SERVER_DESTINATION: /var/www/rimmer-blog/
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build the Next.js app
        run: npm run build
        
      - name: Rsync deployment
        run: rsync -avz --delete .next/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ env.SERVER_DESTINATION }}

      - name: SSH into server and run migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ env.SERVER_DESTINATION }}
            npx prisma migrate deploy
