# Deploys to linode instance
# (Doesn't currently actually deploy)

name: Next.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:	
    runs-on: ubuntu-latest
    
    env:
      SERVER_DESTINATION: /var/www/rimmer-blog/
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build the Next.js app
        run: npm run build
        
        
      - name: Update known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        
      - name: rsync deployments
        uses: contention/rsync-deployments@v2.0.0
        with:
          flags: -avz --delete -e "ssh -p ${{ secrets.PORT }}" 
          # The server user
          user: ${{ secrets.USERNAME }}
          # The deployment target
          host: ${{ secrets.HOST }}
          # The local path to sync
          localpath: .next/
          # The remote path to sync
          remotepath: ${{ env.SERVER_DESTINATION }}
          # The private key
          deploy_key: ${{ secrets.DEPLOY_KEY }}

      - name: SSH into server and run migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ env.SERVER_DESTINATION }}
            npx prisma migrate deploy
